const money = value => new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(value)||0);
const readOrder = () => { try { const order=JSON.parse(localStorage.getItem('fornoOrder')||'null'); if(order){ if(order.item==='Nhoque artesanal')order.item='Massas artesanais'; if(order.item==='Guaraná gelado')order.item='Bebidas'; if(!order.category)order.category=order.item==='Combo da casa'?'combo':order.item==='Bebidas'?'drink':order.item==='Massas artesanais'?'pasta':'pizza'; if(Array.isArray(order.drinks))order.drinks=order.drinks.map(drink=>typeof drink==='string'?(drink==='Guaraná gelado'?'Refrigerante gelado':drink):({...drink,name:drink.name==='Guaraná gelado'?'Refrigerante gelado':drink.name})); } return order; } catch { return null; } };
const saveOrder = order => localStorage.setItem('fornoOrder',JSON.stringify(order));
const escapeHtml = value => String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const toast = message => { const el=document.querySelector('#toast'); if(!el)return; el.textContent=message; el.classList.add('show'); clearTimeout(window.toastTimeout); window.toastTimeout=setTimeout(()=>el.classList.remove('show'),2600); };
async function api(path,data){try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!response.ok)throw new Error('Servidor indisponível');return await response.json();}catch(error){return null;}}
function chooseMenu(item,price){const category=item==='Bebidas'?'drink':item==='Massas artesanais'?'pasta':item==='Combo da casa'?'combo':'pizza';const order={item,base:Number(price),category,flavor:item==='Margherita da horta'?'Margherita da horta':item,crust:'Tradicional',crustPrice:0,drinks:[],name:'',address:'',method:'Pix',status:'Em preparo',createdAt:Date.now(),orderId:null};saveOrder(order);location.href='pedido.html';}
document.querySelectorAll('.menu-card').forEach(card=>{card.addEventListener('click',()=>{if(card.dataset.page){location.href=card.dataset.page;return;}chooseMenu(card.dataset.item,card.dataset.price);});});
document.querySelectorAll('.pizza-add').forEach(button=>button.addEventListener('click',()=>{const order={item:button.dataset.pizza,base:Number(button.dataset.price),category:'pizza',flavor:button.dataset.pizza,crust:'Tradicional',crustPrice:0,drinks:[],name:'',address:'',method:'Pix',status:'Em preparo',createdAt:Date.now(),orderId:null};saveOrder(order);location.href='pedido.html';}));
document.querySelectorAll('.catalog-add').forEach(button=>button.addEventListener('click',()=>{const order={item:button.dataset.name,base:Number(button.dataset.price),category:button.dataset.category,flavor:null,crust:'Tradicional',crustPrice:0,drinks:[],name:'',address:'',method:'Pix',status:'Em preparo',createdAt:Date.now(),orderId:null};saveOrder(order);location.href='pedido.html';}));
// Pedido: personalization and amount calculation.
if(document.querySelector('#confirmOrder')){
 let order=readOrder();if(!order){order={item:'Combo da casa',base:69.9,flavor:'Calabresa artesanal',crust:'Tradicional',crustPrice:0,drinks:[],name:'',address:'',createdAt:Date.now()};saveOrder(order);}
 const pics={'Combo da casa':'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?auto=format&fit=crop&w=280&q=75','Margherita da horta':'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=280&q=75','Massas artesanais':'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=280&q=75','Bebidas':'https://images.unsplash.com/photo-1629203851122-3726ecdf080e?auto=format&fit=crop&w=280&q=75'};
 const descriptions={'Combo da casa':'Pizza grande + bebida 1,5 L','Margherita da horta':'Tomate, mozzarella e manjericão','Massas artesanais':'Massas frescas feitas na casa','Bebidas':'Opções geladinhas para acompanhar'};
 const name=document.querySelector('#itemName'); name.textContent=order.item;const categoryDescription={pizza:'Pizza grande · 8 fatias',drink:'Bebida gelada para acompanhar',pasta:'Massa artesanal feita na casa'};document.querySelector('#itemDescription').textContent=categoryDescription[order.category]||descriptions[order.item]||'Escolha da casa';document.querySelector('#selectedPhoto').style.backgroundImage=`url("${pics[order.item]||pics['Combo da casa']}")`;document.querySelector('#basePrice').textContent=money(order.base);if(order.category&&order.category!=='combo')document.querySelector('#flavorPanel').classList.add('hidden');
 const radio=document.querySelector(`input[name="flavor"][value="${CSS.escape(order.flavor||'Calabresa artesanal')}"]`);if(radio)radio.checked=true;
 document.querySelectorAll('input[name="crust"]').forEach(el=>{el.checked=el.value===(order.crust||'Tradicional');});document.querySelectorAll('input[name="drink"]').forEach(el=>{el.checked=(order.drinks||[]).some(drink=>(typeof drink==='string'?drink:drink.name)===el.value);});
 function calc(){const selectedFlavor=document.querySelector('input[name="flavor"]:checked');const flavorExtra=order.category==='combo'&&selectedFlavor?.value==='Quatro queijos'?6:0;const selectedCrust=document.querySelector('input[name="crust"]:checked');const crustExtra=Number(selectedCrust?.dataset.price||0);const drinks=[...document.querySelectorAll('input[name="drink"]:checked')].map(el=>({name:el.value,price:Number(el.dataset.price)}));const total=Number(order.base)+flavorExtra+crustExtra+drinks.reduce((sum,d)=>sum+d.price,0);order.flavor=order.category==='combo'?selectedFlavor?.value:(order.category==='pizza'?order.item:null);order.crust=selectedCrust?.value;order.crustPrice=crustExtra;order.drinks=drinks;saveOrder(order);document.querySelector('#summaryItem').textContent=order.item;document.querySelector('#summaryBase').textContent=money(order.base);const extras=[];if(flavorExtra)extras.push(['Borda quatro queijos',flavorExtra]);if(crustExtra)extras.push([`Borda ${order.crust}`,crustExtra]);drinks.forEach(d=>extras.push([d.name,d.price]));document.querySelector('#summaryExtras').innerHTML=extras.map(([title,price])=>`<div class="summary-line"><span>${escapeHtml(title)}</span><strong>${money(price)}</strong></div>`).join('');document.querySelector('#summaryTotal').textContent=money(total);return total;}
 document.querySelectorAll('input[name="flavor"],input[name="crust"],input[name="drink"]').forEach(el=>el.addEventListener('change',calc));calc();
 document.querySelector('#changeItem').addEventListener('click',()=>location.href='cardapio.html');
 document.querySelector('#confirmOrder').addEventListener('click',async()=>{const customer=document.querySelector('#customerName').value.trim();const address=document.querySelector('#customerAddress').value.trim();if(!customer||!address){toast('Informe seu nome e endereço para continuar.');(!customer?document.querySelector('#customerName'):document.querySelector('#customerAddress')).focus();return;}order.name=customer;order.address=address;order.total=calc();const result=await api('/api/orders',order);if(result?.orderId)order.orderId=result.orderId;saveOrder(order);location.href='pagamento.html';});
}
// Payment choices: simulated only. No card secrets are captured or transmitted.
if(document.querySelector('#generatePix')){
 const order=readOrder()||{item:'Combo da casa',base:69.9,total:69.9,drinks:[]};const total=Number(order.total||order.base||0);document.querySelector('#paymentTotal').textContent=money(total);const summary=document.querySelector('#paymentSummary');const rows=[[order.item,order.base||total],...(order.crustPrice?[[`Borda ${order.crust}`,order.crustPrice]]:[]),...(order.drinks||[]).map(d=>[d.name,d.price])];summary.innerHTML=rows.map(([title,price])=>`<div class="summary-line"><span>${escapeHtml(title)}</span><strong>${money(price)}</strong></div>`).join('');document.querySelector('#paymentSummaryTotal').textContent=money(total);
 const hideAll=()=>document.querySelectorAll('.pay-content').forEach(el=>el.classList.add('hidden'));document.querySelectorAll('.pay-tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.pay-tab').forEach(t=>t.classList.toggle('active',t===tab));hideAll();if(tab.dataset.method==='pix')document.querySelector('#payPix').classList.remove('hidden');if(tab.dataset.method==='credit'||tab.dataset.method==='debit'){document.querySelector('#cardTitle').textContent=tab.dataset.method==='credit'?'Cartão de crédito':'Cartão de débito';document.querySelector('#payCard').classList.remove('hidden');}if(tab.dataset.method==='cash')document.querySelector('#payCash').classList.remove('hidden');order.method=tab.dataset.method;saveOrder(order);}));
 document.querySelector('#generatePix').addEventListener('click',async()=>{const qr=document.querySelector('#qrFrame');qr.innerHTML='<div class="qr-loading">Gerando código…</div>';const result=await api('/api/payment/pix',{orderId:order.orderId,total});const payload=result?.payload||`DEMO-FORNO-${Date.now()}-${total.toFixed(2)}`;qr.innerHTML='';const img=document.createElement('img');img.alt='QR Code Pix demonstrativo';img.src='https://api.qrserver.com/v1/create-qr-code/?size=240x240&data='+encodeURIComponent(payload);img.onerror=()=>{qr.innerHTML='<div class="qr-loading">QR demonstrativo<br>indisponível offline</div>';};qr.appendChild(img);document.querySelector('#generatePix').textContent='QR Code gerado ✓';document.querySelector('#payPix').insertAdjacentHTML('beforeend','<div class="demo-alert pix-notice">QR demonstrativo, sem cobrança real. Em produção, conecte a um provedor Pix para validar o pagamento.</div><button class="button button-dark full-button" id="pixDone">Concluir demonstração →</button>');document.querySelector('#pixDone').addEventListener('click',()=>{hideAll();document.querySelector('#pixSuccess').classList.remove('hidden');});});
 document.querySelector('#cardNumber').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,16).replace(/(\d{4})(?=\d)/g,'$1 ');});document.querySelector('#cardExpiry').addEventListener('input',e=>{const v=e.target.value.replace(/\D/g,'').slice(0,4);e.target.value=v.length>2?v.slice(0,2)+'/'+v.slice(2):v;});
 document.querySelector('#simulateCard').addEventListener('click',()=>{const number=document.querySelector('#cardNumber').value.replace(/\D/g,'');const holder=document.querySelector('#cardHolder').value.trim();const expiry=document.querySelector('#cardExpiry').value;if(number.length<13||!holder||!/^\d{2}\/\d{2}$/.test(expiry)){toast('Preencha os dados demonstrativos do cartão.');return;}hideAll();document.querySelector('#cardSuccess').classList.remove('hidden');order.method=document.querySelector('.pay-tab.active').dataset.method;saveOrder(order);});
 document.querySelector('#needsChange').addEventListener('change',e=>document.querySelector('#changeField').classList.toggle('hidden',!e.target.checked));document.querySelector('#confirmCash').addEventListener('click',()=>{hideAll();document.querySelector('#cardSuccess').classList.remove('hidden');document.querySelector('#cardSuccess h2').textContent='Pedido confirmado!';document.querySelector('#cardSuccess p').textContent='Pagamento combinado para a entrega.';order.method='cash';saveOrder(order);});
 const finish=async()=>{if(!order.orderId){const result=await api('/api/orders',{...order,name:order.name||'Cliente',address:order.address||'Endereço de demonstração'});if(result?.orderId)order.orderId=result.orderId;}saveOrder(order);location.href='acompanhamento.html';};document.querySelector('#finishPayment').addEventListener('click',finish);document.querySelector('#finishCard').addEventListener('click',finish);
}
// Tracking timer and optional chat API; offline mode still works in this browser.
if(document.querySelector('#countdown')){
 const order=readOrder()||{name:'',address:'',total:69.9};document.querySelector('#trackGreeting').textContent=`${order.name?order.name+', ':''}a cozinha já recebeu seu pedido.`;document.querySelector('#chatName').textContent=order.name||'tudo bem';document.querySelector('#trackAddress').textContent=order.address||'Endereço informado no pedido';document.querySelector('#orderNumber').textContent=order.orderId?`#${order.orderId}`:'#'+String(Math.floor(Date.now()/1000)%10000).padStart(4,'0');
 const ends=(Number(order.createdAt)||Date.now())+45*60*1000;function tick(){const remaining=Math.max(0,ends-Date.now());const m=Math.floor(remaining/60000);const s=Math.floor((remaining%60000)/1000);document.querySelector('#countdown').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;document.querySelector('#timerProgress').style.width=`${Math.max(0,remaining/(45*60*1000)*100)}%`;if(remaining===0)document.querySelector('.timer-card small').textContent='Seu pedido deve estar chegando';}tick();setInterval(tick,1000);
 const messages=document.querySelector('#chatMessages');const form=document.querySelector('#chatForm');const input=document.querySelector('#chatInput');const addMessage=(text,type='sent',time='Agora')=>{const div=document.createElement('div');div.className='message '+type;const p=document.createElement('p');p.textContent=text;const t=document.createElement('time');t.textContent=time;div.append(p,t);messages.append(div);messages.scrollTop=messages.scrollHeight;};
 form.addEventListener('submit',async event=>{event.preventDefault();const text=input.value.trim();if(!text)return;addMessage(text);input.value='';const result=await api('/api/chat',{orderId:order.orderId,name:order.name,message:text});if(result?.reply)addMessage(result.reply,'received');});
 if(order.orderId){fetch(`/api/chat?orderId=${encodeURIComponent(order.orderId)}`).then(r=>r.ok?r.json():null).then(data=>{if(data?.messages?.length){messages.querySelectorAll('.message').forEach(m=>m.remove());data.messages.forEach(m=>addMessage(m.message,m.sender==='customer'?'sent':'received',m.time||'Agora'));}}).catch(()=>{});}
}
if(document.querySelector('#reservationForm')){
 const form=document.querySelector('#reservationForm');const dateField=document.querySelector('#reservationDate');const localDate=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);dateField.min=localDate;
 form.addEventListener('submit',async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form).entries());const result=await api('/api/reservations',data);if(!result)localStorage.setItem('fornoReservation',JSON.stringify({...data,createdAt:Date.now()}));const displayDate=new Date(`${data.date}T12:00:00`).toLocaleDateString('pt-BR',{day:'2-digit',month:'long'});document.querySelector('#reservationConfirmation').textContent=`${data.name}, sua solicitação para ${data.guests} em ${displayDate}, às ${data.time}, foi registrada nesta demonstração. A equipe não recebeu os dados e nenhuma reserva real foi feita.`;document.querySelector('#reservationResult').classList.remove('hidden');document.querySelector('#reservationResult').scrollIntoView({behavior:'smooth',block:'center'});});
}

// Beverage menu category filters.
document.querySelectorAll('[data-drink-filter]').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.drinkFilter;document.querySelectorAll('[data-drink-filter]').forEach(tab=>{const active=tab===button;tab.classList.toggle('active',active);tab.setAttribute('aria-pressed',String(active));});document.querySelectorAll('[data-drink-kind]').forEach(card=>{card.hidden=filter!=='all'&&card.dataset.drinkKind!==filter;});}));
